export const QUICK_START_PRESETS = [
  { label: "🏥 Healthcare", settings: { subject: 'Healthcare Professional', imageMedium: 'Photography', visualType: 'Ultra Realistic', environment: 'Hospital / Clinic', colorMood: 'Warm & Golden' } },
  { label: "🍲 Food", settings: { subject: 'Still life / Food & Drink', imageMedium: 'Photography', visualType: 'Hyper Detailed', environment: 'White Background', colorMood: 'Neutral & Earthy' } },
  { label: "💼 Business", settings: { subject: 'Business Professional', imageMedium: 'Photography', visualType: 'Ultra Realistic', environment: 'Modern Office', colorMood: 'Cool & Clinical' } },
  { label: "🎨 3D Icon", settings: { subject: 'Product / Object Only', imageMedium: '3D & CGI', visualType: 'Premium 3D Icon', environment: 'White Background', colorMood: 'Default / Auto' } },
  { label: "🐾 Pets & Animals", settings: { subject: 'Domestic Pet (Cat, Dog, etc.)', imageMedium: 'Photography', visualType: 'Natural Light', environment: 'Outdoor Park / Nature', colorMood: 'Warm & Golden' } },
  { label: "🌲 Landscape", settings: { subject: 'Background / Landscape only', imageMedium: 'Photography', visualType: 'Cinematic', environment: 'Outdoor Park / Nature', colorMood: 'Default / Auto' } },
  { label: "🤝 Teamwork", settings: { subject: 'Business Team', imageMedium: 'Photography', visualType: 'Natural Light', environment: 'Modern Office', colorMood: 'Cool & Clinical' } },
  { label: "📱 Content Creator", settings: { subject: 'Content Creator / Influencer', imageMedium: 'Photography', visualType: 'Action / Dynamic', environment: 'Cozy Cafe / Coffee Shop', colorMood: 'High Contrast / Dramatic' } },
  { label: "👩‍💻 Developer", settings: { subject: 'Tech developer', imageMedium: 'Photography', visualType: 'Cinematic', environment: 'Modern Office', colorMood: 'Cool & Clinical' } },
  { label: "🛍️ Fashion", settings: { subject: 'E-commerce Fashion Model', imageMedium: 'Photography', visualType: 'Editorial / High Fashion', environment: 'Studio Setting', colorMood: 'High Contrast / Dramatic' } },
  { label: "👨‍👩‍👧 Family", settings: { subject: 'Family group', imageMedium: 'Photography', visualType: 'Natural Light', environment: 'Cozy Home / Living Room', colorMood: 'Warm & Golden' } },
  { label: "🍔 Fast Food", settings: { subject: 'Still life / Food & Drink', imageMedium: 'Photography', visualType: 'Pop Art / Colorful', environment: 'Restaurant / Cafe', colorMood: 'Vibrant & Saturated' } },
  { label: "🔬 Scientist", settings: { subject: 'Scientist / Researcher', imageMedium: 'Photography', visualType: 'Ultra Realistic', environment: 'Hospital / Clinic', colorMood: 'Cool & Clinical' } },
  { label: "🏋️ Fitness", settings: { subject: 'Fitness enthusiast', imageMedium: 'Photography', visualType: 'Action / Dynamic', environment: 'Gym / Fitness Center', colorMood: 'High Contrast / Dramatic' } },
  { label: "🎓 Student", settings: { subject: 'Student / Academic', imageMedium: 'Photography', visualType: 'Natural Light', environment: 'Library / Study', colorMood: 'Soft & Muted' } },
  { label: "🚚 Logistics", settings: { subject: 'Delivery Person / Logistics', imageMedium: 'Photography', visualType: 'Documentary', environment: 'Industrial / Warehouse', colorMood: 'Neutral & Earthy' } },
  { label: "🦁 Wildlife", settings: { subject: 'Wild Animal (Tiger, Lion, etc.)', imageMedium: 'Photography', visualType: 'Macro / Close-up', environment: 'Outdoor Park / Nature', colorMood: 'Natural / Auto' } },
  { label: "📦 Product", settings: { subject: 'Product / Object Only', imageMedium: 'Photography', visualType: 'Minimalist', environment: 'White Background', colorMood: 'Bright & Airy' } },
  { label: "👨‍🍳 Chef", settings: { subject: 'Chef / Kitchen Staff', imageMedium: 'Photography', visualType: 'Hyper Detailed', environment: 'Restaurant / Cafe', colorMood: 'Warm & Golden' } },
  { label: "👷 Construction", settings: { subject: 'Construction Worker', imageMedium: 'Photography', visualType: 'Documentary', environment: 'Industrial / Warehouse', colorMood: 'High Contrast / Dramatic' } },
  { label: "🧑‍🏫 Teacher", settings: { subject: 'Teacher / Educator', imageMedium: 'Photography', visualType: 'Natural Light', environment: 'Library / Study', colorMood: 'Bright & Airy' } },
  { label: "💑 Romance", settings: { subject: 'Romantic Couple', imageMedium: 'Photography', visualType: 'Cinematic', environment: 'Beach / Ocean', colorMood: 'Warm & Golden' } },
  { label: "👵 Senior", settings: { subject: 'Senior citizen', imageMedium: 'Photography', visualType: 'Portrait', environment: 'Cozy Home / Living Room', colorMood: 'Soft & Muted' } },
  { label: "🎉 Party", settings: { subject: 'Group of Friends', imageMedium: 'Photography', visualType: 'Action / Dynamic', environment: 'Bar / Club', colorMood: 'Vibrant & Saturated' } },
  { label: "👶 Baby", settings: { subject: 'Baby / Toddler', imageMedium: 'Photography', visualType: 'Soft Focus / Dreamy', environment: 'Cozy Home / Living Room', colorMood: 'Soft & Muted' } },
  { label: "🛒 Retail", settings: { subject: 'Retail Worker / Shop Staff', imageMedium: 'Photography', visualType: 'Bright / High Key', environment: 'Retail Store / Supermarket', colorMood: 'Bright & Airy' } },
  { label: "🧑‍🎨 Artist", settings: { subject: 'Creative person', imageMedium: 'Photography', visualType: 'Moody / Dark', environment: 'Studio Setting', colorMood: 'Moody / Dark' } },
  { label: "🎮 Gaming 3D", settings: { subject: 'Product / Object Only', imageMedium: '3D & CGI', visualType: 'Cyberpunk / Neon', environment: 'Dark / Black Background', colorMood: 'Vibrant & Saturated' } },
  { label: "🌿 Nature 3D", settings: { subject: 'Background / Landscape only', imageMedium: '3D & CGI', visualType: 'Claymorphism', environment: 'Outdoor Park / Nature', colorMood: 'Neutral & Earthy' } },
  { label: "🤖 Sci-Fi", settings: { subject: 'Product / Object Only', imageMedium: 'Digital Art / Illustration', visualType: 'Cyberpunk / Neon', environment: 'Urban / City Street', colorMood: 'Cool & Clinical' } },
  { label: "🧚 Fantasy", settings: { subject: 'Background / Landscape only', imageMedium: 'Digital Art / Illustration', visualType: 'Anime / Manga', environment: 'Forest / Woods', colorMood: 'Vibrant & Saturated' } },
  { label: "☕ Cozy Cafe", settings: { subject: 'Still life / Food & Drink', imageMedium: 'Photography', visualType: 'Warm / Inviting', environment: 'Cozy Cafe / Coffee Shop', colorMood: 'Warm & Golden' } },
  { label: "🏙️ Cityscape", settings: { subject: 'Background / Landscape only', imageMedium: 'Photography', visualType: 'Cinematic', environment: 'Urban / City Street', colorMood: 'Moody / Dark' } },
  { label: "🚘 Automotive", settings: { subject: 'Product / Object Only', imageMedium: 'Photography', visualType: 'Hyper Detailed', environment: 'Urban / City Street', colorMood: 'High Contrast / Dramatic' } },
  { label: "🏥 Clinic", settings: { subject: 'Doctor / Medical Team', imageMedium: 'Photography', visualType: 'Ultra Realistic', environment: 'Hospital / Clinic', colorMood: 'Cool & Clinical' } },
  { label: "👴 Caregiver", settings: { subject: 'Caregiver / Home Nurse', imageMedium: 'Photography', visualType: 'Natural Light', environment: 'Cozy Home / Living Room', colorMood: 'Soft & Muted' } },
  { label: "🛠️ Manual Work", settings: { subject: 'Manual Laborer / Factory Worker', imageMedium: 'Photography', visualType: 'Documentary', environment: 'Industrial / Warehouse', colorMood: 'Neutral & Earthy' } },
  { label: "🧘 Mindfulness", settings: { subject: 'Casual person', imageMedium: 'Photography', visualType: 'Soft Focus / Dreamy', environment: 'Beach / Ocean', colorMood: 'Bright & Airy' } },
  { label: "🐱 Cute Pet", settings: { subject: 'Domestic Pet (Cat, Dog, etc.)', imageMedium: 'Photography', visualType: 'Macro / Close-up', environment: 'Cozy Home / Living Room', colorMood: 'Warm & Golden' } },
  { label: "🌌 Night Sky", settings: { subject: 'Background / Landscape only', imageMedium: 'Photography', visualType: 'Astrophotography', environment: 'Outdoor Park / Nature', colorMood: 'Moody / Dark' } },
  { label: "💎 Luxury", settings: { subject: 'Product / Object Only', imageMedium: 'Photography', visualType: 'Premium 3D Icon', environment: 'Dark / Black Background', colorMood: 'High Contrast / Dramatic' } },
  { label: "🎸 Concert", settings: { subject: 'Group of Friends', imageMedium: 'Photography', visualType: 'Action / Dynamic', environment: 'Bar / Club', colorMood: 'Vibrant & Saturated' } },
  { label: "🏖️ Vacation", settings: { subject: 'Family group', imageMedium: 'Photography', visualType: 'Bright / High Key', environment: 'Beach / Ocean', colorMood: 'Bright & Airy' } },
  { label: "🚀 Startup", settings: { subject: 'Business Team', imageMedium: 'Photography', visualType: 'Cinematic', environment: 'Modern Office', colorMood: 'Cool & Clinical' } },
  { label: "👩‍🍼 Parenting", settings: { subject: 'Parent & Child', imageMedium: 'Photography', visualType: 'Natural Light', environment: 'Cozy Home / Living Room', colorMood: 'Soft & Muted' } }
];
